void bcalveto_IDR_L()
{
//=========Macro generated from canvas: c11/
//=========  (Mon Apr 22 16:55:32 2019) by ROOT version6.08/06
   TCanvas *c11 = new TCanvas("c11", "",415,1103,400,400);
   gStyle->SetOptStat(0);
   c11->Range(-0.7500001,-2.888515,6.75,11.18058);
   c11->SetFillColor(0);
   c11->SetBorderMode(0);
   c11->SetBorderSize(2);
   c11->SetLogy();
   c11->SetTopMargin(0.05);
   c11->SetBottomMargin(0.15);
   c11->SetFrameBorderMode(0);
   c11->SetFrameBorderMode(0);
   
   THStack *hNBcalClusters_all = new THStack();
   hNBcalClusters_all->SetName("hNBcalClusters_all");
   hNBcalClusters_all->SetTitle(";Number of BCal clusters;");
   hNBcalClusters_all->SetMinimum(1);
   hNBcalClusters_all->SetMaximum(1e+10);
   
   TH1F *hNBcalClusters_all_stack_1 = new TH1F("hNBcalClusters_all_stack_1","",6,0,6);
   hNBcalClusters_all_stack_1->SetMinimum(0.1666667);
   hNBcalClusters_all_stack_1->SetMaximum(3e+10);
   hNBcalClusters_all_stack_1->SetDirectory(0);
   hNBcalClusters_all_stack_1->SetStats(0);
   hNBcalClusters_all_stack_1->SetLineWidth(3);
   hNBcalClusters_all_stack_1->SetMarkerStyle(20);
   hNBcalClusters_all_stack_1->SetMarkerSize(1.3);
   hNBcalClusters_all_stack_1->GetXaxis()->SetTitle("Number of BCal clusters");
   hNBcalClusters_all_stack_1->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_all_stack_1->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_1->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_1->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_1->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_1->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_all_stack_1->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_all_stack_1->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_1->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_1->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_1->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_1->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_all_stack_1->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_all_stack_1->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_1->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_1->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_1->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_1->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_all_stack_1->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->SetHistogram(hNBcalClusters_all_stack_1);
   
   
   TH1F *hNBcalClusters1ISR_nungSum__1 = new TH1F("hNBcalClusters1ISR_nungSum__1","",6,0,6);
   hNBcalClusters1ISR_nungSum__1->SetBinContent(1,2278113);
   hNBcalClusters1ISR_nungSum__1->SetBinContent(2,237778.9);
   hNBcalClusters1ISR_nungSum__1->SetBinContent(3,10045.81);
   hNBcalClusters1ISR_nungSum__1->SetBinContent(4,278.1919);
   hNBcalClusters1ISR_nungSum__1->SetBinContent(5,2.511719);
   hNBcalClusters1ISR_nungSum__1->SetEntries(2526219);
   hNBcalClusters1ISR_nungSum__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum__1->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum__1->SetLineWidth(3);
   hNBcalClusters1ISR_nungSum__1->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum__1->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__1->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum__1->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum__1->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClusters1ISR_nungSum,"");
   
   TH1F *hNBcalClustersMultiISR_nungSum__2 = new TH1F("hNBcalClustersMultiISR_nungSum__2","",6,0,6);
   hNBcalClustersMultiISR_nungSum__2->SetBinContent(1,393002.8);
   hNBcalClustersMultiISR_nungSum__2->SetBinContent(2,141139.2);
   hNBcalClustersMultiISR_nungSum__2->SetBinContent(3,10404.2);
   hNBcalClustersMultiISR_nungSum__2->SetBinContent(4,292.2021);
   hNBcalClustersMultiISR_nungSum__2->SetBinContent(5,13.96614);
   hNBcalClustersMultiISR_nungSum__2->SetEntries(544852.3);
   hNBcalClustersMultiISR_nungSum__2->SetStats(0);

   ci = TColor::GetColor("#006600");
   hNBcalClustersMultiISR_nungSum__2->SetFillColor(ci);
   hNBcalClustersMultiISR_nungSum__2->SetLineWidth(3);
   hNBcalClustersMultiISR_nungSum__2->SetMarkerStyle(20);
   hNBcalClustersMultiISR_nungSum__2->SetMarkerSize(1.3);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__2->GetXaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum__2->GetYaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum__2->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClustersMultiISR_nungSum,"");
   
   TH1F *hNBcalClusters_bhabhangSum__3 = new TH1F("hNBcalClusters_bhabhangSum__3","",6,0,6);
   hNBcalClusters_bhabhangSum__3->SetBinContent(1,67012.15);
   hNBcalClusters_bhabhangSum__3->SetBinContent(2,843187.1);
   hNBcalClusters_bhabhangSum__3->SetBinContent(3,1689000);
   hNBcalClusters_bhabhangSum__3->SetBinContent(4,81217.87);
   hNBcalClusters_bhabhangSum__3->SetBinContent(5,1983.371);
   hNBcalClusters_bhabhangSum__3->SetBinContent(6,36.6701);
   hNBcalClusters_bhabhangSum__3->SetEntries(2682437);
   hNBcalClusters_bhabhangSum__3->SetStats(0);

   ci = TColor::GetColor("#ff9966");
   hNBcalClusters_bhabhangSum__3->SetFillColor(ci);
   hNBcalClusters_bhabhangSum__3->SetLineWidth(3);
   hNBcalClusters_bhabhangSum__3->SetMarkerStyle(20);
   hNBcalClusters_bhabhangSum__3->SetMarkerSize(1.3);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClusters_bhabhangSum,"");
   hNBcalClusters_all->Draw("");
   
   TLegend *leg = new TLegend(0.5,0.85,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   leg->Draw();
   
   leg = new TLegend(0.61,0.6,0.86,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hNBcalClusters_bhabhangSum","e^{+}e^{-}+N#gamma (N>0)","f");

   ci = TColor::GetColor("#ff9966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClustersMultiISR_nungSum","#nu#nu+N#gamma (N>1)","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClusters1ISR_nungSum","#nu#nu+1#gamma","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.24,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c11->Modified();
   c11->cd();
   c11->SetSelected(c11);
}
