void bcalveto_eeNg_comp()
{
//=========Macro generated from canvas: c3/
//=========  (Fri Aug 30 10:30:43 2019) by ROOT version6.08/06
   TCanvas *c3 = new TCanvas("c3", "",1049,1163,400,400);
   gStyle->SetOptStat(0);
   c3->Range(-1.459459,-0.7152624,6.648649,6.831362);
   c3->SetFillColor(10);
   c3->SetBorderMode(0);
   c3->SetBorderSize(2);
   c3->SetLogy();
   c3->SetTickx(1);
   c3->SetTicky(1);
   c3->SetLeftMargin(0.18);
   c3->SetRightMargin(0.08);
   c3->SetTopMargin(0.05);
   c3->SetBottomMargin(0.15);
   c3->SetFrameLineWidth(3);
   c3->SetFrameBorderMode(0);
   c3->SetFrameLineWidth(3);
   c3->SetFrameBorderMode(0);
   
   TH1F *hNBcalClusters_l5_bhabhangSum__7 = new TH1F("hNBcalClusters_l5_bhabhangSum__7","",6,0,6);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(1,33341.79);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(2,652874.8);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(3,1501350);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(4,40777.14);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(5,1007.896);
   hNBcalClusters_l5_bhabhangSum__7->SetBinContent(6,5.221091);
   hNBcalClusters_l5_bhabhangSum__7->SetEntries(2229356);
   hNBcalClusters_l5_bhabhangSum__7->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   hNBcalClusters_l5_bhabhangSum__7->SetLineColor(ci);
   hNBcalClusters_l5_bhabhangSum__7->SetLineWidth(2);
   hNBcalClusters_l5_bhabhangSum__7->SetMarkerStyle(20);
   hNBcalClusters_l5_bhabhangSum__7->SetMarkerSize(1.3);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum__7->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetTitle("Events");
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_l5_bhabhangSum__7->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_l5_bhabhangSum__7->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum__7->Draw("");
   
   TH1F *hNBcalClusters_s5_bhabhangSum__8 = new TH1F("hNBcalClusters_s5_bhabhangSum__8","",6,0,6);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(1,34442.94);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(2,658045.6);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(3,1494087);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(4,39249.1);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(5,1007.134);
   hNBcalClusters_s5_bhabhangSum__8->SetBinContent(6,21.05219);
   hNBcalClusters_s5_bhabhangSum__8->SetEntries(2226852);
   hNBcalClusters_s5_bhabhangSum__8->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   hNBcalClusters_s5_bhabhangSum__8->SetLineColor(ci);
   hNBcalClusters_s5_bhabhangSum__8->SetLineStyle(4);
   hNBcalClusters_s5_bhabhangSum__8->SetLineWidth(3);
   hNBcalClusters_s5_bhabhangSum__8->SetMarkerStyle(20);
   hNBcalClusters_s5_bhabhangSum__8->SetMarkerSize(1.3);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_s5_bhabhangSum__8->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetTitle("Events");
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_s5_bhabhangSum__8->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_s5_bhabhangSum__8->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_s5_bhabhangSum__8->Draw("same");
   
   TLegend *leg = new TLegend(0.71,0.6,0.95,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hNBcalClusters1ISR_l5_nungSum","IDR-L","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClusters1ISR_s5_nungSum","IDR-S","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(4);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.57,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,0.73,"e^{+}e^{-}+N#gamma");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hNBcalClusters_l5_bhabhangSum_copy__9 = new TH1F("hNBcalClusters_l5_bhabhangSum_copy__9","",6,0,6);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(1,33341.79);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(2,652874.8);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(3,1501350);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(4,40777.14);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(5,1007.896);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetBinContent(6,5.221091);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetEntries(2229356);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetDirectory(0);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   hNBcalClusters_l5_bhabhangSum_copy__9->SetLineColor(ci);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetLineWidth(2);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetMarkerStyle(20);
   hNBcalClusters_l5_bhabhangSum_copy__9->SetMarkerSize(1.3);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetTitle("Events");
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_l5_bhabhangSum_copy__9->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_l5_bhabhangSum_copy__9->Draw("sameaxis");
   c3->Modified();
   c3->cd();
   c3->SetSelected(c3);
}
