void bcalveto_IDR_S()
{
//=========Macro generated from canvas: c11/
//=========  (Mon Apr 22 16:55:36 2019) by ROOT version6.08/06
   TCanvas *c11 = new TCanvas("c11", "",415,1103,400,400);
   gStyle->SetOptStat(0);
   c11->Range(-1.36,-2.888515,6.64,11.18058);
   c11->SetFillColor(10);
   c11->SetBorderMode(0);
   c11->SetBorderSize(2);
   c11->SetLogy();
   c11->SetTickx(1);
   c11->SetTicky(1);
   c11->SetLeftMargin(0.17);
   c11->SetRightMargin(0.08);
   c11->SetTopMargin(0.05);
   c11->SetBottomMargin(0.15);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   
   THStack *hNBcalClusters_all = new THStack();
   hNBcalClusters_all->SetName("hNBcalClusters_all");
   hNBcalClusters_all->SetTitle(";Number of BCal clusters;");
   hNBcalClusters_all->SetMinimum(1);
   hNBcalClusters_all->SetMaximum(1e+10);
   
   TH1F *hNBcalClusters_all_stack_2 = new TH1F("hNBcalClusters_all_stack_2","",6,0,6);
   hNBcalClusters_all_stack_2->SetMinimum(0.1666667);
   hNBcalClusters_all_stack_2->SetMaximum(3e+10);
   hNBcalClusters_all_stack_2->SetDirectory(0);
   hNBcalClusters_all_stack_2->SetStats(0);
   hNBcalClusters_all_stack_2->SetLineWidth(3);
   hNBcalClusters_all_stack_2->SetMarkerStyle(20);
   hNBcalClusters_all_stack_2->SetMarkerSize(1.3);
   hNBcalClusters_all_stack_2->GetXaxis()->SetTitle("Number of BCal clusters");
   hNBcalClusters_all_stack_2->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_all_stack_2->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_2->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_2->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_2->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_2->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_all_stack_2->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_all_stack_2->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_2->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_2->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_2->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_2->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_all_stack_2->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_all_stack_2->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_all_stack_2->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_all_stack_2->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_all_stack_2->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_all_stack_2->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_all_stack_2->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->SetHistogram(hNBcalClusters_all_stack_2);
   
   
   TH1F *hNBcalClusters1ISR_nungSum__4 = new TH1F("hNBcalClusters1ISR_nungSum__4","",6,0,6);
   hNBcalClusters1ISR_nungSum__4->SetBinContent(1,2464905);
   hNBcalClusters1ISR_nungSum__4->SetBinContent(2,60890.84);
   hNBcalClusters1ISR_nungSum__4->SetBinContent(3,1888.155);
   hNBcalClusters1ISR_nungSum__4->SetBinContent(4,31.78629);
   hNBcalClusters1ISR_nungSum__4->SetEntries(2527716);
   hNBcalClusters1ISR_nungSum__4->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum__4->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum__4->SetLineWidth(3);
   hNBcalClusters1ISR_nungSum__4->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum__4->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__4->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum__4->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum__4->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClusters1ISR_nungSum,"");
   
   TH1F *hNBcalClustersMultiISR_nungSum__5 = new TH1F("hNBcalClustersMultiISR_nungSum__5","",6,0,6);
   hNBcalClustersMultiISR_nungSum__5->SetBinContent(1,428662.8);
   hNBcalClustersMultiISR_nungSum__5->SetBinContent(2,113064.2);
   hNBcalClustersMultiISR_nungSum__5->SetBinContent(3,3536.951);
   hNBcalClustersMultiISR_nungSum__5->SetBinContent(4,108.528);
   hNBcalClustersMultiISR_nungSum__5->SetBinContent(5,0.2093099);
   hNBcalClustersMultiISR_nungSum__5->SetEntries(545372.7);
   hNBcalClustersMultiISR_nungSum__5->SetStats(0);

   ci = TColor::GetColor("#006600");
   hNBcalClustersMultiISR_nungSum__5->SetFillColor(ci);
   hNBcalClustersMultiISR_nungSum__5->SetLineWidth(3);
   hNBcalClustersMultiISR_nungSum__5->SetMarkerStyle(20);
   hNBcalClustersMultiISR_nungSum__5->SetMarkerSize(1.3);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__5->GetXaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum__5->GetYaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum__5->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClustersMultiISR_nungSum,"");
   
   TH1F *hNBcalClusters_bhabhangSum__6 = new TH1F("hNBcalClusters_bhabhangSum__6","",6,0,6);
   hNBcalClusters_bhabhangSum__6->SetBinContent(1,73092.78);
   hNBcalClusters_bhabhangSum__6->SetBinContent(2,875575.3);
   hNBcalClusters_bhabhangSum__6->SetBinContent(3,1680900);
   hNBcalClusters_bhabhangSum__6->SetBinContent(4,47298.16);
   hNBcalClusters_bhabhangSum__6->SetBinContent(5,1250.742);
   hNBcalClusters_bhabhangSum__6->SetBinContent(6,21.05219);
   hNBcalClusters_bhabhangSum__6->SetEntries(2678138);
   hNBcalClusters_bhabhangSum__6->SetStats(0);

   ci = TColor::GetColor("#ff9966");
   hNBcalClusters_bhabhangSum__6->SetFillColor(ci);
   hNBcalClusters_bhabhangSum__6->SetLineWidth(3);
   hNBcalClusters_bhabhangSum__6->SetMarkerStyle(20);
   hNBcalClusters_bhabhangSum__6->SetMarkerSize(1.3);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__6->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__6->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__6->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_all->Add(hNBcalClusters_bhabhangSum,"");
   hNBcalClusters_all->Draw("");
   
   TLegend *leg = new TLegend(0.5,0.85,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   leg->Draw();
   
   leg = new TLegend(0.61,0.6,0.86,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hNBcalClusters_bhabhangSum","e^{+}e^{-}+N#gamma (N>0)","f");

   ci = TColor::GetColor("#ff9966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClustersMultiISR_nungSum","#nu#nu+N#gamma (N>1)","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClusters1ISR_nungSum","#nu#nu+1#gamma","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.24,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   c11->Modified();
   c11->cd();
   c11->SetSelected(c11);
}
