void bcalveto_IDR_L()
{
//=========Macro generated from canvas: c11/
//=========  (Thu Aug 29 16:12:30 2019) by ROOT version6.08/06
   TCanvas *c11 = new TCanvas("c11", "",415,1103,400,400);
   gStyle->SetOptStat(0);
   c11->Range(-1.459459,-1.875,6.648649,10.625);
   c11->SetFillColor(10);
   c11->SetBorderMode(0);
   c11->SetBorderSize(2);
   c11->SetLogy();
   c11->SetTickx(1);
   c11->SetTicky(1);
   c11->SetLeftMargin(0.18);
   c11->SetRightMargin(0.08);
   c11->SetTopMargin(0.05);
   c11->SetBottomMargin(0.15);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   
   TH1F *hNBcalClusters1ISR_nungSum2__1 = new TH1F("hNBcalClusters1ISR_nungSum2__1","",6,0,6);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(1,3529401);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(2,833417.5);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(3,1507047);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(4,40906.76);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(5,1008.736);
   hNBcalClusters1ISR_nungSum2__1->SetBinContent(6,5.221091);
   hNBcalClusters1ISR_nungSum2__1->SetMinimum(1);
   hNBcalClusters1ISR_nungSum2__1->SetMaximum(1e+10);
   hNBcalClusters1ISR_nungSum2__1->SetEntries(5911786);
   hNBcalClusters1ISR_nungSum2__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum2__1->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum2__1->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum2__1->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__1->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetTitle("Events");
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetTitleOffset(1.3);
   hNBcalClusters1ISR_nungSum2__1->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum2__1->GetZaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__1->Draw("");
   
   TH1F *hNBcalClustersMultiISR_nungSum2__2 = new TH1F("hNBcalClustersMultiISR_nungSum2__2","",6,0,6);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(1,537720.5);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(2,763567.6);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(3,1504818);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(4,40860.54);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(5,1008.736);
   hNBcalClustersMultiISR_nungSum2__2->SetBinContent(6,5.221091);
   hNBcalClustersMultiISR_nungSum2__2->SetEntries(2847980);
   hNBcalClustersMultiISR_nungSum2__2->SetStats(0);

   ci = TColor::GetColor("#006600");
   hNBcalClustersMultiISR_nungSum2__2->SetFillColor(ci);
   hNBcalClustersMultiISR_nungSum2__2->SetMarkerStyle(20);
   hNBcalClustersMultiISR_nungSum2__2->SetMarkerSize(1.3);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__2->GetXaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum2__2->GetYaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum2__2->GetZaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__2->Draw("same");
   
   TH1F *hNBcalClusters_bhabhangSum__3 = new TH1F("hNBcalClusters_bhabhangSum__3","",6,0,6);
   hNBcalClusters_bhabhangSum__3->SetBinContent(1,33341.79);
   hNBcalClusters_bhabhangSum__3->SetBinContent(2,652874.8);
   hNBcalClusters_bhabhangSum__3->SetBinContent(3,1501350);
   hNBcalClusters_bhabhangSum__3->SetBinContent(4,40777.14);
   hNBcalClusters_bhabhangSum__3->SetBinContent(5,1007.896);
   hNBcalClusters_bhabhangSum__3->SetBinContent(6,5.221091);
   hNBcalClusters_bhabhangSum__3->SetEntries(2229356);
   hNBcalClusters_bhabhangSum__3->SetStats(0);

   ci = TColor::GetColor("#ff9966");
   hNBcalClusters_bhabhangSum__3->SetFillColor(ci);
   hNBcalClusters_bhabhangSum__3->SetMarkerStyle(20);
   hNBcalClusters_bhabhangSum__3->SetMarkerSize(1.3);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__3->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__3->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__3->Draw("same");
   
   TLegend *leg = new TLegend(0.5,0.85,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   leg->Draw();
   
   leg = new TLegend(0.61,0.6,0.86,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hNBcalClusters1ISR_nungSum2","#nu#nu+1#gamma","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClustersMultiISR_nungSum2","#nu#nu+N#gamma (N>1)","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClusters_bhabhangSum","e^{+}e^{-}+N#gamma (N>0)","f");

   ci = TColor::GetColor("#ff9966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.24,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.24,0.75,"IDR-L");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hNBcalClusters1ISR_nungSum2_copy__4 = new TH1F("hNBcalClusters1ISR_nungSum2_copy__4","",6,0,6);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(1,3529401);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(2,833417.5);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(3,1507047);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(4,40906.76);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(5,1008.736);
   hNBcalClusters1ISR_nungSum2_copy__4->SetBinContent(6,5.221091);
   hNBcalClusters1ISR_nungSum2_copy__4->SetMinimum(1);
   hNBcalClusters1ISR_nungSum2_copy__4->SetMaximum(1e+10);
   hNBcalClusters1ISR_nungSum2_copy__4->SetEntries(5911786);
   hNBcalClusters1ISR_nungSum2_copy__4->SetDirectory(0);
   hNBcalClusters1ISR_nungSum2_copy__4->SetStats(0);

   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum2_copy__4->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum2_copy__4->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum2_copy__4->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__4->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetTitle("Events");
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetTitleOffset(1.3);
   hNBcalClusters1ISR_nungSum2_copy__4->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum2_copy__4->GetZaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__4->Draw("sameaxis");
   c11->Modified();
   c11->cd();
   c11->SetSelected(c11);
}
