void bcalveto_IDR_S()
{
//=========Macro generated from canvas: c11/
//=========  (Thu Aug 29 16:12:34 2019) by ROOT version6.08/06
   TCanvas *c11 = new TCanvas("c11", "",415,1103,400,400);
   gStyle->SetOptStat(0);
   c11->Range(-1.459459,-1.875,6.648649,10.625);
   c11->SetFillColor(10);
   c11->SetBorderMode(0);
   c11->SetBorderSize(2);
   c11->SetLogy();
   c11->SetTickx(1);
   c11->SetTicky(1);
   c11->SetLeftMargin(0.18);
   c11->SetRightMargin(0.08);
   c11->SetTopMargin(0.05);
   c11->SetBottomMargin(0.15);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   c11->SetFrameLineWidth(3);
   c11->SetFrameBorderMode(0);
   
   TH1F *hNBcalClusters1ISR_nungSum2__5 = new TH1F("hNBcalClusters1ISR_nungSum2__5","",6,0,6);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(1,3524996);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(2,833161.3);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(3,1499237);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(4,39380.24);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(5,1007.343);
   hNBcalClusters1ISR_nungSum2__5->SetBinContent(6,21.05219);
   hNBcalClusters1ISR_nungSum2__5->SetMinimum(1);
   hNBcalClusters1ISR_nungSum2__5->SetMaximum(1e+10);
   hNBcalClusters1ISR_nungSum2__5->SetEntries(5897802);
   hNBcalClusters1ISR_nungSum2__5->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum2__5->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum2__5->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum2__5->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__5->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetTitle("Events");
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetTitleOffset(1.3);
   hNBcalClusters1ISR_nungSum2__5->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum2__5->GetZaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2__5->Draw("");
   
   TH1F *hNBcalClustersMultiISR_nungSum2__6 = new TH1F("hNBcalClustersMultiISR_nungSum2__6","",6,0,6);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(1,539799.1);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(2,766051.4);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(3,1497228);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(4,39342.12);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(5,1007.343);
   hNBcalClustersMultiISR_nungSum2__6->SetBinContent(6,21.05219);
   hNBcalClustersMultiISR_nungSum2__6->SetEntries(2843449);
   hNBcalClustersMultiISR_nungSum2__6->SetStats(0);

   ci = TColor::GetColor("#006600");
   hNBcalClustersMultiISR_nungSum2__6->SetFillColor(ci);
   hNBcalClustersMultiISR_nungSum2__6->SetMarkerStyle(20);
   hNBcalClustersMultiISR_nungSum2__6->SetMarkerSize(1.3);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__6->GetXaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetNdivisions(506);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum2__6->GetYaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetLabelFont(42);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetLabelSize(0.06);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetTitleSize(0.07);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClustersMultiISR_nungSum2__6->GetZaxis()->SetTitleFont(42);
   hNBcalClustersMultiISR_nungSum2__6->Draw("same");
   
   TH1F *hNBcalClusters_bhabhangSum__7 = new TH1F("hNBcalClusters_bhabhangSum__7","",6,0,6);
   hNBcalClusters_bhabhangSum__7->SetBinContent(1,34442.94);
   hNBcalClusters_bhabhangSum__7->SetBinContent(2,658045.6);
   hNBcalClusters_bhabhangSum__7->SetBinContent(3,1494087);
   hNBcalClusters_bhabhangSum__7->SetBinContent(4,39249.1);
   hNBcalClusters_bhabhangSum__7->SetBinContent(5,1007.134);
   hNBcalClusters_bhabhangSum__7->SetBinContent(6,21.05219);
   hNBcalClusters_bhabhangSum__7->SetEntries(2226852);
   hNBcalClusters_bhabhangSum__7->SetStats(0);

   ci = TColor::GetColor("#ff9966");
   hNBcalClusters_bhabhangSum__7->SetFillColor(ci);
   hNBcalClusters_bhabhangSum__7->SetMarkerStyle(20);
   hNBcalClusters_bhabhangSum__7->SetMarkerSize(1.3);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__7->GetXaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetNdivisions(506);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__7->GetYaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetLabelFont(42);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters_bhabhangSum__7->GetZaxis()->SetTitleFont(42);
   hNBcalClusters_bhabhangSum__7->Draw("same");
   
   TLegend *leg = new TLegend(0.5,0.85,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   leg->Draw();
   
   leg = new TLegend(0.61,0.6,0.86,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(3);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hNBcalClusters1ISR_nungSum2","#nu#nu+1#gamma","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClustersMultiISR_nungSum2","#nu#nu+N#gamma (N>1)","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hNBcalClusters_bhabhangSum","e^{+}e^{-}+N#gamma (N>0)","f");

   ci = TColor::GetColor("#ff9966");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.24,0.8,"#scale[1.5]{#font[62]{ILD}} #font[42]{preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.24,0.75,"IDR-S");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *hNBcalClusters1ISR_nungSum2_copy__8 = new TH1F("hNBcalClusters1ISR_nungSum2_copy__8","",6,0,6);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(1,3524996);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(2,833161.3);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(3,1499237);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(4,39380.24);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(5,1007.343);
   hNBcalClusters1ISR_nungSum2_copy__8->SetBinContent(6,21.05219);
   hNBcalClusters1ISR_nungSum2_copy__8->SetMinimum(1);
   hNBcalClusters1ISR_nungSum2_copy__8->SetMaximum(1e+10);
   hNBcalClusters1ISR_nungSum2_copy__8->SetEntries(5897802);
   hNBcalClusters1ISR_nungSum2_copy__8->SetDirectory(0);
   hNBcalClusters1ISR_nungSum2_copy__8->SetStats(0);

   ci = TColor::GetColor("#cccc00");
   hNBcalClusters1ISR_nungSum2_copy__8->SetFillColor(ci);
   hNBcalClusters1ISR_nungSum2_copy__8->SetMarkerStyle(20);
   hNBcalClusters1ISR_nungSum2_copy__8->SetMarkerSize(1.3);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetTitle("# of BCal clusters");
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__8->GetXaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetTitle("Events");
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetNdivisions(506);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetTitleOffset(1.3);
   hNBcalClusters1ISR_nungSum2_copy__8->GetYaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetLabelFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetLabelOffset(0.015);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetLabelSize(0.06);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetTitleSize(0.07);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetTitleOffset(1.1);
   hNBcalClusters1ISR_nungSum2_copy__8->GetZaxis()->SetTitleFont(42);
   hNBcalClusters1ISR_nungSum2_copy__8->Draw("sameaxis");
   c11->Modified();
   c11->cd();
   c11->SetSelected(c11);
}
